### ISSUE TITLE
Risk's BetterBrime Ideas

### ISSUE THREAD

**Issue by Riskqify** [4uss/BetterBrime#1]
Should add timestamps for messages :D

[added]

**Comment by Riskqify** [comment]
- Light mode (For Cam) [added]
- OBS Dock 
- Readable Name Colors
- Chatbox [added]

**Comment by anKordii** [comment]
> * Light mode (For Cam)
> * OBS Dock
> * Readable Usernames
> * Chatbox

Light mode (For Cam)? just a white version of site?
