### ISSUE TITLE
please, add a emoji resolution limit

### ISSUE THREAD

**Issue by alexei4884** [4uss/BetterBrime#2]
ahh... im sorry, i add a very... very huge emoji 2048x2048, I published the wrong file. heh...
and can you made a delete button?
![image](https://user-images.githubusercontent.com/63174820/123275937-6c1c0980-d50d-11eb-817b-1bada07fdec2.png)

**Comment by anKordii** [comment]
Hi, you can remove emote from your channel using button "Remove from channel" and upload a new version of emote with the same name. The wrong one i will delete by myself but you don't need to wait until someone delete it :) just upload a new one!

In the next update site will have automatic resize to 3 sizes 112x112, 64x64 and 32x32 
Currently we recommend upload emotes at size 32x32 
![image](https://user-images.githubusercontent.com/34755589/123421206-db9d0200-d5bc-11eb-812e-63dc579854ad.png)
