### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by BotKendrick** [4uss/BetterBrime#4]
I have a few quality of life ideas.
-Allow to search for the person who uploaded emotes.
-Adding a search to the Dashboard page
-Making it easier to add the emote to a channel just on the emote page rather than clicking into a new page and having to go back at the top of the previous page after adding it.  ~ add the "add to channel"/"remove from channel" button under the @user and not have it refresh/redirect the page.

**Comment by anKordii** [comment]
# IT'S LIVE!
![image](https://user-images.githubusercontent.com/34755589/129931810-3dfc60bb-0a7f-4925-b720-3275729f3af3.png)
![image](https://user-images.githubusercontent.com/34755589/129931883-7122b33f-773a-4829-bda3-98d40978130a.png)
